apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeshandis-mvc
  namespace: codeshandis
  labels:
    app: codeshandis-mvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codeshandis-mvc
  template:
    metadata:
      labels:
        app: codeshandis-mvc
    spec:
      containers:
      - name: codeshandis-mvc
        image: tkswiss/codeshandis-mvc:v1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
