apiVersion: v1
kind: Service
metadata:
  name: codeshandis-mvc-service
  namespace: codeshandis
spec:
  selector:
    app: codeshandis-mvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Change to NodePort if needed
